### ISSUE TITLE
SimplifiedProfileNotes causes crash when loading profile pop-out or user profile in DMs

### ISSUE THREAD

**Issue by RobinRMC** [Sqaaakoi/Vencord#3]
Workaround is to first open the full profile of a random user. After having done this, the crash doesn't occur anymore.

**Comment by Sqaaakoi** [comment]
I don't see any crashes (on canary) but I do see that it's failing to require the modules that have the stock class names and as such it doesn't even try to load at all. Will keep testing

**Comment by Sqaaakoi** [comment]
Stable is exploding because it does load that code and can't find the class name modules

**Comment by Sqaaakoi** [comment]
The class name module still exists.

**Comment by Sqaaakoi** [comment]
Seems to work after updating the extractAndLoadChunksLazy find

**Comment by Sqaaakoi** [comment]
Works for me now. If you keep having issues downstream, please leave a comment here (or mention me) with error logs
